### PR TITLE
Cleaned up and added jpeg support

### PR DESCRIPTION
**Pull request by ahmadhadwan**
Closed open file pointers, free`d memory allocated on the heap, and
added jpeg support using stb_image.

### CODE REVIEW

**Comment by mekb-turtle** [comment]
what does the changes in Makefile do? what's `$@` and `$^`?

**Comment by ahmadhadwan** [comment]
$@ is the name of the target(rule), and $^ is the name of the prerequisites that the rule depends on. And yes sizeof(uint8_t) is always going to be one. It doesn't change anything, but it could be used to clear things up, and avoid magic numbers.

**Comment by mekb-turtle** [comment]
I don't think `free` is needed on `int`s if they're scoped with `{` `}`

**Comment by mekb-turtle** [comment]
the jpeg image seems to be read incorrectly
test

**Comment by mekb-turtle** [comment]
okay i've fixed it, merged in #2

**Comment by sophuric** [comment]
i kinda just used this Makefile and stuck with it, it's easy to edit and stuff, @ahmadhadwan let me know if you don't want me to use it

**Pull request closed without merging**
